// MuniLK.Application.Documents.DTOs/DocumentResponse.cs
using System;

namespace MuniLK.Application.Documents.DTOs
{
    public class DocumentResponse
    {
        public Guid Id { get; set; }
        public string FileName { get; set; } = string.Empty;
        public string FileExtension { get; set; } = string.Empty;
        public string ContentType { get; set; } = string.Empty;
        public long FileSize { get; set; }
        public string? Description { get; set; }

        public Guid DocumentTypeId { get; set; }
        // You might want to include the DocumentType Name/DisplayName here if you often need it
        // public string DocumentTypeName { get; set; } = string.Empty;

        // Optionally include status ID and/or name
        public Guid? DocumentStatusId { get; set; }
        // public string? DocumentStatusName { get; set; }

        public DateTime UploadedDate { get; set; }
        public string? UploadedBy { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public string? LastModifiedBy { get; set; }

        // Important: DO NOT expose BlobPath directly to the client.
        // Instead, provide a download URL if needed (generated by a separate service/query).
        // public string DownloadUrl { get; set; }
    }
}