// MuniLK.Infrastructure/Data/Configurations/ContactConfiguration.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MuniLK.Domain.Entities; // Adjust namespace

namespace MuniLK.Infrastructure.Data.Configurations
{
    public class ContactConfiguration : IEntityTypeConfiguration<MuniLK.Domain.Entities.ContactEntities.Contact>
    {
        public void Configure(EntityTypeBuilder<MuniLK.Domain.Entities.ContactEntities.Contact> builder)
        {
            builder.HasKey(e => e.Id); // Assuming Id is your primary key

            builder.Property(e => e.Id)
                   .ValueGeneratedOnAdd(); // Ensure GUIDs are generated by DB

            builder.Property(e => e.CreatedAt)
                   .HasDefaultValueSql("GETUTCDATE()"); // Example for SQL Server

            builder.Property(e => e.IsActive)
                   .HasDefaultValue(true);

            // Unique indexes
            builder.HasIndex(e => e.NIC).IsUnique();
            builder.HasIndex(e => e.Email).IsUnique();
            builder.HasIndex(e => e.PhoneNumber).IsUnique();

            // Configure navigation property for PropertyOwners
            builder.HasMany(c => c.PropertyOwners)
                   .WithOne(po => po.Contact)
                   .HasForeignKey(po => po.ContactId)
                   .OnDelete(DeleteBehavior.Restrict); // Or .Cascade
        }
    }
}