// MuniLK.Infrastructure/Data/Configurations/PropertyConfiguration.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MuniLK.Domain.Entities; // Adjust namespace

namespace MuniLK.Infrastructure.Data.Configurations
{
    public class PropertyConfiguration : IEntityTypeConfiguration<Property>
    {
        public void Configure(EntityTypeBuilder<Property> builder)
        {
            builder.HasKey(p => p.Id); // Assuming Id is your primary key

            builder.Property(p => p.Id)
                   .ValueGeneratedOnAdd(); // Ensure GUIDs are generated by DB

            builder.Property(p => p.Address)
                   .IsRequired(); // Example: Address is required

            // Configure navigation property for PropertyOwners
            builder.HasMany(p => p.PropertyOwners)
                   .WithOne(po => po.Property)
                   .HasForeignKey(po => po.PropertyId)
                   .OnDelete(DeleteBehavior.Restrict); // Or .Cascade
        }
    }
}